---
- name: Configure machine
  hosts: localhost
  roles:
    - dotfiles
    - zsh
    - rust
    - mise
    - name: flatpak
      when: ansible_distribution != "MacOSX"
      tags:
        - flatpak
        - never
  tasks:
    - name: Clone repos
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
      loop:
        - {
            repo: "https://github.com/joseph62/Scripts.git",
            dest: ".local/opt/Scripts",
          }
    - name: Install general packages from package manager
      ansible.builtin.package:
        name:
          - gcc
          - curl
          - htop
          - rlwrap
          - neovim
          - httpie
          - jq
          - jo
          - tldr
          - fzf
        state: present
      become: "{{ ansible_distribution != 'MacOSX' }}"
      ignore_errors: true
    - name: Install python build packages for macos
      ansible.builtin.package:
        name:
          - openssl
          - readline
          - sqlite3
          - xz
          - zlib
          - tcl-tk
        state: present
      when: ansible_distribution == 'MacOSX'
    - name: Install python build packages for ubuntu
      ansible.builtin.package:
        name:
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - curl
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev
        state: present
      when: ansible_distribution == 'Ubuntu'
      become: true
    - name: Install python build packages for fedora
      ansible.builtin.package:
        name:
          - gcc
          - python3-devel
          - zlib
          - zlib-devel
          - patch
          - bzip2
          - bzip2-devel
          - readline-devel
          - sqlite
          - sqlite-devel
          - openssl-devel
          - tk-devel
          - libffi-devel
          - xz-devel
          - libuuid-devel
          - gdbm-libs
          - libnsl2
        state: present
      when: ansible_distribution == 'Fedora'
      become: true
    - name: Install packages from cargo
      community.general.cargo:
        name:
          - zoxide
          - fd-find
          - exa
          - ripgrep
          - bat
          - cargo-update
        state: present
      environment:
        PATH: "{{ lookup('env', 'HOME') }}/.cargo/bin:{{ lookup('env', 'PATH') }}"
    - name: Install tools using mise
      ansible.builtin.shell: "mise install"
      when: "item not in lookup('ansible.builtin.env', 'PATH').split(':') | map('basename')"
    - name: Install tools using uv
      ansible.builtin.shell: "uv tool install {{ item }}"
      when: "item not in lookup('ansible.builtin.env', 'PATH').split(':') | map('basename')"
      loop:
        - ruff
        - thefuck
      environment:
        PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ lookup('env', 'PATH') }}"
