---
- name: Configure machine
  hosts: localhost
  roles:
    - dotfiles
    - zsh
    - rust
    - rtx
    - name: flatpak
      when: ansible_distribution != "MacOSX"
      tags: flatpak
  tasks:
    - name: Clone repos
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
      loop:
        - { repo: "https://github.com/joseph62/Scripts.git", dest: ".local/opt/Scripts" }
        - { repo: "https://github.com/VundleVim/Vundle.vim.git", dest: ".vim/bundle/Vundle.vim"}
    - name: Install general packages from package manager
      ansible.builtin.package:
        name:
          - gcc
          - curl
          - htop
          - rlwrap
          - vim
          - httpie
          - jq
          - jo
          - tldr
          - fzf
        state: present
      become: "{{ ansible_distribution != 'MacOSX' }}"
      ignore_errors: true
    - name: Install fedora packages from package manager
      ansible.builtin.package:
        name:
          - python3-devel
        state: present
      when: ansible_distribution == 'Fedora'
    - name: Install packages from pip
      ansible.builtin.pip:
        name:
          - thefuck
        state: present
    - name: Install packages from cargo
      community.general.cargo:
        name:
          - zoxide
          - fd-find
          - exa
          - ripgrep
          - bat
        state: present
